name: Label Issues Based on Project Status

on:
  project_card:
    types: [moved]

jobs:
  label_by_project_column:
    runs-on: ubuntu-latest
    steps:
      - name: Get project card details
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const columnId = context.payload.project_card.column_id;
            const cardId = context.payload.project_card.id;
            const cardContentUrl = context.payload.project_card.content_url;

            if (!cardContentUrl) {
              console.log('Card is note, not issue. Skipping.');
              return;
            }

            const contentRes = await fetch(cardContentUrl, {
              headers: { Authorization: `token ${process.env.GITHUB_TOKEN}` }
            });
            const content = await contentRes.json();

            // Get all project columns
            const project_id = context.payload.project_card.project_id;
            const columns = await github.rest.projects.listColumns({
              project_id
            });

            const column = columns.data.find(c => c.id === columnId);

            if (!column) {
              console.log('Column not found');
              return;
            }

            const labelName = column.name;

            // Add label to issue
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: content.number,
              labels: [labelName]
            });

            console.log(`Added label ${labelName} to issue #${content.number}`);
